Add orientation tracking for Roboy's hands
Roboy/TeleportVR pull request #24
Opened 2021-04-15 10:06 UTC by rasaford

2021-04-15 16:01 UTC, missxa requested changes
exclude files not directly relevant for the changes, like XR Rig.prefab and the settings files

2021-04-16 08:28 UTC, rasaford commented on Assets/Roboy/Wheelchair/Scripts/OrientationOffset.cs
> +        Quaternion offset = Quaternion.Euler(-189.118f, -8.403992f, 15.2381f);
Aparrently const Quartenion is not allowed, but I defined the rotations to be const

2021-04-19 11:03 UTC, rasaford commented
- [ ] Add checkbox to turn orientation tracking on- and off

2021-04-19 12:14 UTC, rasaford commented
Added a track offset checkbox, which enables / disables orienation tracking on the OrientationOffsets

![Capture](https://user-images.githubusercontent.com/15111467/115234576-7b4f9700-a119-11eb-8952-3668c64f3bb9.JPG)

2021-04-20 10:13 UTC, missxa requested changes

2021-04-20 10:13 UTC, missxa commented on Assets/Roboy/Wheelchair/Scripts/OrientationOffset.cs
> +        const float rx = -189.118f, ry = -8.403992f, rz = 15.2381f;
no need to declare this in every update. these values never change, so they can be moved to start() or just static private members

2021-04-20 10:13 UTC, missxa commented on Assets/Roboy/Wheelchair/Scripts/OrientationOffset.cs
> +            orientationObjective.Weight = 1;
where is this variable used?

2021-04-21 19:55 UTC, missxa approved these changes

2021-04-22 08:23 UTC, merged