Sense glove integration
Roboy/TeleportVR pull request #25
Opened 2021-04-20 12:12 UTC by rasaford

Closes XSF-45

2021-04-21 19:54 UTC, missxa commented
where is the whole senseglove folder coming from? 
if it's a git repository -> add it as a submodule
if it's a unity asset store package -> add it to readme and to the gdrive folder

2021-04-26 16:17 UTC, missxa reviewed
it seems like the current approach excludes the control using oculus controllers, which is not the goal. we want to extend the current solution to use another input method - senseglove

so it would be expected to have, for a example, a scripting define symbol SENSEGLOVE that would enable/disable scripts that have sense glove as a dependency and switch finger input method from controller grip button to senseglove

also, when using the gloves the operator will not be able to press the index trigger button to enable the arm IK tracking. i believe this was not addressed in the code yet

2021-04-27 07:46 UTC, rasaford commented on Assets/Roboy/RoboyFK/CopyTransfrom.cs
> +public class CopyTransfrom : MonoBehaviour
It copies the global position and rotation from `wrist_{left|right}_axis2` to the senseglove hand model. This makes it easier to test the hand model's behavior

2021-04-27 07:48 UTC, rasaford commented on Assets/Roboy/RoboyFK/FKHingeJoint.cs
> +using System.Collections;
Just a place for the my two new scripts `CopyTransform` and `FKJointLink` if you have a better idea of where they should go, I'm happy to move them.

2021-04-27 07:49 UTC, rasaford commented on Assets/Roboy/Wheelchair/Scripts/OrientationOffset.cs
> +using System.Collections;
Yes, but I based this PR on the previous one to also be able to test orientation tracking and senseglove integration at the same time.

2021-04-27 08:00 UTC, rasaford commented on Assets/Scripts/InputManager.cs
> +            List<List<string>> jointSets = new List<List<string>>()
C# seems to not allow `List<T>` to be const. I've made it readonly for additional type safety. `ImmutableArray<T>` might be an option, but that needs to be installed as an additional packacke as far, as I can tell: 

https://stackoverflow.com/questions/33889521/a-const-list-in-c-sharp

2021-04-27 09:00 UTC, rasaford commented on Assets/Scripts/InputManager.cs
> +                double range = L2Distance(min, max);
no, I just didn't want to convert lists to vector2,3,4, yet :)

2021-04-27 09:12 UTC, rasaford commented on Assets/AnimusClient/Example/Scripts/UnityAnimusClient.cs
> +    public BioIK.BioIK _myRightHand;
good spot, they aren't

2021-04-27 09:15 UTC, rasaford commented on Assets/AnimusClient/Example/Scripts/UnityAnimusClient.cs
> +            // right_hand, left_hand
I didn't think of that. I've now added it back in

2021-04-27 09:20 UTC, rasaford commented
In Summary, I did not consider that control via oculus controllers is still necessary when adding the senseglove integration. I've now added added those parts back in.

SenseGlove integration is enabled by setting the symbol `SENSEGLOVE`, if it's set finger positions will be sent via Animus, if not oculus controllers are used as before. 

On the user not being able to press the trigger buttons while wearing the sense glove, what do you think is a good fix: 
- Always tracking IK position when `SENSEGLOVE` is set
- Having them do some gesture to enable / disable tracking

Thanks for your detailed feedback tough! I could really see that you took some time to look at my code :)

2021-05-03 15:09 UTC, rasaford commented
TODO: Validate that oculus controller support is still working

2021-05-04 13:20 UTC, rasaford commented
@missxa this is ready for review again, thx

2021-05-09 19:21 UTC, missxa commented
let's keep things clean, can you please remove the training procedure-related commits from this branch and make a new one for senseglove training. since it's not done and i would have some comments on the tutorial

2021-05-09 19:40 UTC, missxa requested changes

2021-05-09 19:40 UTC, missxa commented on Assets/OperatorUserInterface/Scripts/Construct/GrabRoboy.cs
> +//#if SENSEGLOVE
so i'm assuming there was a define symbol senseglove before and  you just commented out things from the previous usages in the project? if that's the case, it's not ideal
were these parts causing issues?

2021-05-09 19:40 UTC, missxa commented on Assets/Roboy/RoboyFK/CopyJointAngle.cs
> +using System.Collections;
RoboyFK is a misleading name, i would suggest to rename it, since the scripts there are not related to FK of the Roboy body. the other 2 folders there contain meshes of the robot body and the wheelchair and some related scripts. Your scripts are not roboy specific, it seems, and can be applied to other objects as well

A better place for your scripts from this folder would be Assets/Scripts/Utils or something along that way

2021-05-09 19:40 UTC, missxa commented on Assets/Roboy/RoboyFK/FKHingeJoint.cs
> +    public class FKHingeJoint : MonoBehaviour
it's not very clear from the name what this class does, inline comments would be great here

2021-05-09 19:40 UTC, missxa commented on Assets/Roboy/Wheelchair/Scripts/OrientationOffset.cs
> +using System.Collections;
why is this script in the wheelchair folder?

2021-05-11 09:23 UTC, rasaford commented on Assets/OperatorUserInterface/Scripts/Construct/GrabRoboy.cs
> +//#if SENSEGLOVE
Possibly we can introduce another symbol, or update the old code

2021-05-12 09:06 UTC, rasaford commented on Assets/Roboy/Wheelchair/Scripts/OrientationOffset.cs
> +using System.Collections;
moved it to `Assets/Scripts/JointTransfer`

2021-05-24 17:08 UTC, missxa commented
force-push is not great - for the future

2021-05-24 17:15 UTC, missxa approved these changes

2021-05-25 12:15 UTC, closed without merging

2021-05-25 12:16 UTC, rasaford commented
This is already merged into the develop branch with #26. Therefore closing this PR and merging develop