Sense glove calibration tutorial
Roboy/TeleportVR pull request #26
Opened 2021-05-10 10:13 UTC by rasaford

Adds calibration for both sensegloves during the Training tutorial

2021-06-01 14:25 UTC, missxa requested changes
please address the comments before merge

2021-06-01 14:25 UTC, missxa commented on Assets/Training/Calibration/HandCalibrator.cs
> +            string right = isRight ? "right" : "left";
hard coded strings in the code, as well as numbers is not great

2021-06-01 14:25 UTC, missxa commented on Assets/Training/Calibration/HandTestStep.cs
> +        public float maxError = 0.5f;
what are the units?

2021-06-01 14:25 UTC, missxa commented on Assets/Training/TutorialSteps.cs
> +        public AudioClips senseGlove;
can we please find a unified way to manage audioclips

2021-06-01 14:25 UTC, missxa commented on Assets/Training/TutorialSteps.cs
> +        public AudioClips senseGlove;
as a sidenote, even if the senseglove is not in use, we can still load the clip imo

2021-06-01 14:25 UTC, missxa commented on Assets/Training/TutorialSteps.cs
> +            Widget notificationWidget = Manager.Instance.FindWidgetWithID(10);
what is the magic 10?

2021-06-01 14:25 UTC, missxa commented on Assets/Training/TutorialSteps.cs
> +            Widget notificationWidget = Manager.Instance.FindWidgetWithID(10);
why are you not using publishnotification function? it's going agains the architecture in mind and introduces another interdependence between project parts

2021-06-01 14:25 UTC, missxa commented on Assets/Training/TutorialSteps.cs
> +                    PublishNotification("Move your right arm and try to touch the green ball");
it's not green really :P

2021-06-02 09:46 UTC, rasaford commented on Assets/Training/Calibration/HandCalibrator.cs
> +            string right = isRight ? "right" : "left";
These checks are removed in the newest version and replace by a class level read only variable.

2021-06-02 09:49 UTC, rasaford commented on Assets/Training/Calibration/HandTestStep.cs
> +        public float maxError = 0.5f;
Squared difference in meters, so `m^2`
Now noted in the tooltip.

2021-06-02 09:51 UTC, rasaford commented on Assets/Training/TutorialSteps.cs
> +        public AudioClips senseGlove;
Fixed the audio clip loading. 

What do you mean by unified way to load audio clips? Currently they are all passed in as Script public variables.

2021-06-02 09:53 UTC, rasaford commented on Assets/Training/TutorialSteps.cs
> +                    PublishNotification("Move your right arm and try to touch the green ball");
changed it to blue ;)

2021-06-07 12:47 UTC, missxa commented on Assets/Training/TutorialSteps.cs
> +            Widget notificationWidget = Manager.Instance.FindWidgetWithID(10);
yes, there's publishnotification function https://github.com/Roboy/TeleportVR/blob/363fd24e3f7e41910f83d24073df6790445edf48/Assets/Training/TutorialSteps.cs#L100
can we try to use that one? you can move it somewhere else if needed
because having 10 all over the code is not ideal, esp if one day we change the order of widgets

2021-06-07 14:16 UTC, rasaford commented on Assets/Training/TutorialSteps.cs
> +            Widget notificationWidget = Manager.Instance.FindWidgetWithID(10);
Of course. Changed it. The one you saw was still left over from testing and could easily be merged with the old one.

2021-07-07 11:48 UTC, merged