Move tracking space to head goal position
Roboy/TeleportVR pull request #29
Opened 2021-05-24 14:28 UTC by rasaford

2021-06-01 13:57 UTC, missxa requested changes

2021-06-01 13:57 UTC, missxa commented on Assets/Scripts/StartCalibrator.cs
> +    public float calibrationTime = 2;
what are the units?

2021-06-01 13:57 UTC, missxa commented on Assets/Scripts/StartCalibrator.cs
> +public class StartCalibrator : MonoBehaviour
add inline comments about what this script is doing

2021-06-04 09:03 UTC, rasaford commented on Assets/Scripts/StartCalibrator.cs
> +    public float calibrationTime = 2;
seconds, added a comment

2021-06-07 12:49 UTC, missxa approved these changes

2021-06-08 08:57 UTC, merged