Immersive telepresence
Roboy/TeleportVR pull request #60
Opened 2023-01-18 19:29 UTC by ZuzkaU

Refactoring of the project.

2023-01-30 14:25 UTC, missxa requested changes
- [ ] add inline comments with explanations to all newly created classes (at least)
- [x] use member class variables in functions called very often (eg from `Update()`) instead of initialising local variables, since it uses up a lot of memory, especially bad on Android
- [ ] address comments re refactoring & data connectors @ZuzkaU 
- [ ] address comments re new webrtc communication @bekleyis95 
- [x] remove unnecessary logs
- [ ] pass user tests by @missxa 
- [x] clean up `.meta~*` files
- [x] move all scripts related to Robody control to `RobodyControl` folder
- [x] move tutorial folder into the training folder
- [x] rename `Widgets` folder to `WidgetsBaseImplementation` or similar, since the name is misleading. For example, clock is a widget
- [x] update README

2023-01-30 17:16 UTC, ZuzkaU commented
- [ ] fix centering the VR Rig on load (it gets centered but is 90 degrees rotated)
- [ ] use B button for recentering again
- [ ] make HUD transparent
- [ ] use the plugin for buttons
- [ ] remove rays from the controllers (only keep them for Settings)
- [ ] icons on the top bar: make clear which state they are in (mic on / off / grayed out if not connected / not in HUD?), add icon for movements
- [ ] don't display the spheres when the data from the camera haven't arrived yet
- [ ] use milky way skybox by default (we should have plugin for that)
- [ ] we need a server name for aiortc instead of a hardcoded IP address

2023-02-06 17:36 UTC, ZuzkaU commented on Assets/Scripts/Tutorial/RightHand.cs
> +    public class RightHand : Step
fac850728ec916a1fad4c0acf21

2023-02-06 17:37 UTC, ZuzkaU commented on Assets/Scripts/Tutorial/MoveHead.cs
> +    public class MoveHead : Step
fac850728ec916a1fad4c0acf21

2023-02-06 17:37 UTC, ZuzkaU commented on Assets/Scripts/Tutorial/LeftHand.cs
> +    public class LeftHand : Step
fac850728ec916a1fad4c0acf21

2023-02-06 18:18 UTC, ZuzkaU commented on Assets/Scripts/DisplayExtensions/ClockWidget.cs
> +            string time = $"{DateTime.Now.Hour:D2}:{DateTime.Now.Minute:D2}:{DateTime.Now.Second:D2}";
https://docs.unity3d.com/Manual/performance-garbage-collection-best-practices.html

2023-02-06 18:22 UTC, ZuzkaU commented on Assets/Scripts/Tutorial/LeftArm.cs
> +using InputDevices.Controllers;
fac850728ec916a1fad4c0acf216b33a321cf9a3

2023-02-06 18:22 UTC, ZuzkaU commented on Assets/Scripts/Tutorial/Done.cs
> +    public class Done : Step
fac850728ec916a1fad4c0acf216b33a321cf9a3

2023-02-06 18:23 UTC, ZuzkaU commented on Assets/Scripts/ServerConnection/Aiortc/aiortcConnector.cs
> +            Debug.Log($"onDataChannel");
dc7d98d55feef0fb79a3a39fb28b2f6e525c7406

2023-02-06 18:31 UTC, ZuzkaU commented on Assets/Scripts/InputDevices/JointTransfer/DrawDebugObj.cs
> +        private IEnumerable<GameObject> getChildren(Transform parent, System.Predicate<GameObject> predicate)
It was in this class originally, I moved the folder JointTransfer from Assets/InputDevices to Asssets/Scripts/InputDevices and did only little changes here.

https://github.com/Roboy/TeleportVR/commit/4380511f6bdcaf459972727d464714416f93f965#diff-b880860836c504b5f3ad0afd241f62acd076cfc6824f0c3637fd713d73cfd427

2023-02-06 18:55 UTC, ZuzkaU commented on Assets/Scripts/InputDevices/Controllers/ControllerInputSystem.cs
> +namespace InputDevices.Controllers
c0b48d39e9c4f2a2150ce2cbc4a5d140254c47b4

2023-02-10 09:23 UTC, ZuzkaU commented on Assets/Scripts/InputDevices/Scripts/HandManager.cs
> +using System.Collections;
Only the location. https://github.com/Roboy/TeleportVR/blob/553654a0e02cf72600ca52ed509bf30cd24f31aa/Assets/InputDevices/Scripts/HandManager.cs

2023-02-10 09:29 UTC, ZuzkaU commented on Assets/Scripts/InputDevices/Scripts/XROffset.cs
> +using System.Collections;
19ac860d32fccec00

2023-02-10 09:31 UTC, ZuzkaU commented on Assets/Scripts/ServerConnection/Aiortc/ImtpEncoder.cs
> +public class ImtpEncoder : MonoBehaviour
2ac8647

2023-02-10 11:21 UTC, ZuzkaU commented on Assets/Scripts/Widgets/BasicWidgets.cs
> +    public class BasicWidgets : Singleton<BasicWidgets>
This is *not* a widget manager. This is an implementation of a few widgets which are so essential that they should be present every time the Widgets component is in use. Also, if you name every other component "manager", it doesn't increase clarity of what it actually manages.

2023-02-20 16:30 UTC, missxa commented on Assets/Scripts/DisplayExtensions/ClockWidget.cs
> +            string time = $"{DateTime.Now.Hour:D2}:{DateTime.Now.Minute:D2}:{DateTime.Now.Second:D2}";
@ZuzkaU  yes, this supports my comment above. or did you have any objections?

2023-03-01 18:07 UTC, missxa approved these changes

2023-03-02 08:23 UTC, merged